# Generated by Django 3.1.3 on 2020-11-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201128_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='projectscreenshot',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='projecturl',
        ),
    ]
